### ISSUE TITLE
Problem: we do not have an estimate and scope of work for offline functionality

### ISSUE THREAD

**Issue by jrwdunham** [dativebase/dativebase#5]
# Estimate and Task Breakdown: DativeBase Offline Functionality

Given that [DativeBase should work offline](https://github.com/dativebase/dativebase/issues/4), this issue documents the high-level subtasks required in order to achieve this and provides an estimate of developer time needed to complete these tasks. 

**Total time estimate: 30 days (240 hours)**

## Definition of Done

Offline functionality will be considered done when a user can easily install DativeBase as a desktop application and optionally set one or more of its offline client OLD instances to automatically synchronize with one or more online master OLD instances when Internet connectivity is restored.

## Task Breakdown and Time Estimates

- [ ] [DativeTop](https://github.com/dativebase/dativetop) should have basic functionality. **10 days.**
  - [ ] It should be easy to install DativeTop, e.g., by downloading and double clicking a .dmg or .exe file.
  - [ ] DativeTop should have a simple GUI for managing (i.e., creating, deleting) OLD instances.
  - [ ] DativeTop should have feature parity with DativeBase (to the extent possible, e.g., morphological parser functionality may not be easily possible without advanced installation).
- [ ] [The OLD](https://github.com/dativebase/old-pyramid) must be able to automatically sync itself with a master instance when Internet connectivity is restored. **15 days.** This requires that we do the following.
  - [ ] Allow an OLD to be configured as an offline client (slave) of an online master.
  - [ ] Implement a poor man's append-only event log so that every state mutation is recorded in an immutable ledger and in temporal order so that the state of an OLD instance can always be reconstructed by replaying the mutation events in order.
  - [ ] Write "rebase and sync" logic which detects Internet connectivity and does the following:
     a. downloads the master (server-side) event log, 
     b. stores current local state so that the sync can be aborted if need be,
     c. returns local state to where it was at the time of the fork from master,
     d. plays the master's new events (since the client's fork) against the local state,
     e. plays the clients new events (since the client's fork) against the master,
     f. plays the clients new events (since the client's fork) against the client's new state, and
     g. destroys the failsafe stored local state from step (b).
  - [ ] Write tests that confirm that offline/online sync works.
- [ ] Write documentation for all of the above. **2 days.**
- [ ] Deploy all of the above. **3 days.**
  - [ ] Serve DativeTop binaries for easy download.
  - [ ] Cause DativeTop binaries to be published based on triggers, e.g., new version released and all tests passed. (CI/CD).
